image: docker:20.10

services:
  - docker:20.10-dind

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_dev:
  stage: build
  script: 
    - docker-compose build web_dev
    - docker-compose push web_dev
  only:
    - develop

build_prod:
  stage: build
  script: 
    - docker-compose build web_prod
    - docker-compose push web_prod
  only:
    - main
