image: "gitlab/dind"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build_dev:
  stage: build
  image: "node:16-alpine3.12"
  before_script:
    - 'which curl || ( apk update && apk add curl jq git )'
    - git status
    - git pull
    - git submodule update --init --recursive
    - curl -L https://github.com/gohugoio/hugo/releases/download/v0.83.1/hugo_0.83.1_Linux-64bit.tar.gz | tar -xz && mv hugo /usr/local/bin/hugo
    - npm install
    - ls -acl
  script: 
    - npx gulp build -f gulpfile_dev.js
  artifacts:
    paths:
      - public
    expire_in: 2 days
  only:
    - develop

build_prod:
  stage: build
  image: "node:16-alpine3.12"
  before_script:
    - 'which curl || ( apk update && apk add curl jq )'
    - curl -L https://github.com/gohugoio/hugo/releases/download/v0.83.1/hugo_0.83.1_Linux-64bit.tar.gz | tar -xz && mv hugo /usr/local/bin/hugo
    - npm install
  script: 
    - npx gulp build -f gulpfile_prod.js
  artifacts:
    paths:
      - public
    expire_in: 2 days
  only:
    - main

deploy_dev:
  image: alpine:3.12
  stage: deploy
  before_script:
    - apk add --no-cache rsync openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa orthos.pod.cvut.cz >> ~/.ssh/known_hosts
  script:
    - rsync -az --omit-dir-times --no-o --no-g --no-perms public/ gitlab-deployer@orthos.pod.cvut.cz:/var/www/new.pod.cvut.cz/web/ --delete
  only:
    - develop
  when: on_success

deploy_prod:
  image: alpine:3.12
  stage: deploy
  before_script:
    - apk add --no-cache rsync openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa orthos.pod.cvut.cz >> ~/.ssh/known_hosts
  script:
    - rsync -az --omit-dir-times --no-o --no-g --no-perms public/ gitlab-deployer@orthos.pod.cvut.cz:/var/www/pod.cvut.cz/web/ --delete
  only:
    - main
  when: on_success
