image: registry.pod.cvut.cz/cache/library/docker:20.10

services:
  - registry.pod.cvut.cz/cache/library/docker:20.10-dind

variables:
  DOCKER_HOST: tcp://docker:2375

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.pod.cvut.cz

build_dev:
  stage: build
  script: 
    - docker-compose build web_dev
    - docker-compose push web_dev
  only:
    - develop

build_prod:
  stage: build
  script: 
    - docker-compose build web_prod
    - docker-compose push web_prod
  only:
    - main
