image: registry.pod.cvut.cz/cache/docker/compose:alpine-1.29.2

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.pod.cvut.cz

build_dev:
  stage: build
  script:
    - DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build web_dev
    - docker-compose push web_dev
  only:
    - develop

build_prod:
  stage: build
  script: 
    - DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build web_prod
    - docker-compose push web_prod
  only:
    - main
