image: "gitlab/dind"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.pod.cvut.cz

build_dev:
  stage: build
  script: 
    - docker-compose build web_dev
    - docker-compose push web_dev
  only:
    - develop

build_prod:
  stage: build
  script: 
    - docker-compose build web_prod
    - docker-compose push web_prod
  only:
    - main
