version: '3.7'

services:
  web_prod:
    ports:
      - 8004:80
    restart: unless-stopped
    image: registry.pod.cvut.cz/internal/pod-o-lee/main-web-prod
  web_dev:
    ports:
      - 8005:80
    restart: unless-stopped
    image: registry.pod.cvut.cz/internal/pod-o-lee/main-web-dev
