version: '3.7'

services:
  web_prod:
    build:
      context: .
      target: web_prod
      cache_from: 
        - registry.pod.cvut.cz/internal/pod-o-lee/main-web-prod
    ports:
      - 8004:80
    restart: unless-stopped
    image: registry.pod.cvut.cz/internal/pod-o-lee/main-web-prod
  web_dev:
    build:
      context: .
      target: web_dev
      cache_from: 
        - registry.pod.cvut.cz/internal/pod-o-lee/main-web-dev
    ports:
      - 8005:80
    restart: unless-stopped
    image: registry.pod.cvut.cz/internal/pod-o-lee/main-web-dev
